name: kadai_info_flutter
description: A new Flutter project.
publish_to: 'none'
version: 8.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^1.0.0
  flutter_hooks: ^0.18.0
  flex_color_scheme: ^5.0.0
  equatable: ^2.0.3
  intl: ^0.17.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  uuid: ^3.0.4
  dio: ^4.0.1
  webview_flutter: ^3.0.2
  firebase_core: ^1.10.2
  firebase_messaging: ^11.1.0
  pull_to_refresh: ^2.0.0
  android_intent: ^2.0.2
  package_info: ^2.0.2
  device_info_plus: ^3.1.1
  app_settings: ^4.1.1
  firebase_remote_config: ^2.0.5
  launch_review: ^3.0.1
  url_launcher: ^6.0.6
  animations: ^2.0.2
  nfc_manager: ^3.1.0
  cached_network_image: ^3.1.0+1
  flutter_cache_manager: ^3.1.3
  freezed_annotation: ^2.0.1
  cloud_firestore: ^3.1.1
  connectivity: ^3.0.6
  firebase_database: ^9.0.12
  import_sorter: ^4.6.0
  flutter_native_splash: ^2.1.6
  firebase_analytics: ^9.1.6
  settings_ui: ^2.0.2
  http: ^0.13.4
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  freezed: ^2.0.2
  flutter_launcher_icons: ^0.9.2
  json_serializable: ^6.1.6

flutter_icons:
  android: true
  ios: true
  image_path: "asset/icon/icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - asset/
    - asset/image/
    - asset/icon/
    - asset/image/circle/
    - asset/image/binanbijo2021/
    - asset/logo/binanbijo2021/
